### ISSUE TITLE
Inconsistency in AllParameters::readParamLine

### ISSUE THREAD

**Issue by jan-provaznik** [bbopt/nomad#110]
The [comment](https://github.com/bbopt/nomad/blob/master/src/Param/AllParameters.hpp#L252) claims the function [AllParameters::readParamLine](https://github.com/bbopt/nomad/blob/master/src/Param/AllParameters.hpp#L254) throws for unknown parameters.

The implementation, however, does not throw anything. Instead, the errors are [printed out](https://github.com/bbopt/nomad/blob/master/src/Param/AllParameters.cpp#L147) to the standard error stream.

**Comment by ctribes** [comment]
The comment is changed for the next release. 

Note that unrecognized parameters can trigger an exception or not (just a message) when doing RunParams::checkAndComply. This is managed by REJECT_UNKNOWN_PARAMETERS.

**Comment by jan-provaznik** [comment]
Thanks for the clarification and the fix.

**Comment by ctribes** [comment]
I am also changing the default value for REJECT_UNKNOWN_PARAMETERS in NOMAD 4.3 (now it is true instead of false) so that an exception is triggered for unregistered params.
