### ISSUE TITLE
Strange behaviour using PyNOMAD

### ISSUE THREAD

**Issue by asortino** [bbopt/nomad#121]
Hi everyone,
I'm writing an application for which NOMAD is used as MIP solver. Calling PyNOMAD (v4.3.1) recurrently, a failure happens:

```
result = PyNomad.optimize(objective, x0, lb, ub, params)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
E   AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?
PyNomad.pyx:192: AttributeError
```
A similar problem was already mentioned and solved in #53, but, in the new version, the problem seems to be there again.

(As suggested in #53, a simple workaround, that works for me, is to create a copy of the parameter list)

Best regards,
Alessio

**Comment by jan-provaznik** [comment]
It seems that the changes made in https://github.com/bbopt/nomad/pull/80 have been reverted with the commit d7c1b52f0add9cf51cedc89c188e9a822be69594. The [diff](https://github.com/bbopt/nomad/commit/d7c1b52f0add9cf51cedc89c188e9a822be69594#diff-25e959ff9c15b0ff812b64e1f283e8c901cc1415cb3503ab9ab502078806994a) confirms this. I'll make another patch and a pull request again to address this problem.
