### ISSUE TITLE
Just some helpful guidelines on building nomad's MATLAB interface

### ISSUE THREAD

**Issue by ultimatecheun** [bbopt/nomad#128]
As per Christophe's request that I share my approach/instructions on how to build nomad's MATLAB interface, I believe that the following details would be super-useful for anyone struggling to realize this.

**Using the NOMAD Optimizer which requires building Nomad with MinGW compiler using CMake**
-	Update MATLAB’s MinGW using this link: (https://www.mathworks.com/support/requirements/supported-compilers.html)
Follow on-screen instructions (for example, dragging and dropping in MATLAB’s command window)
NB:   Updates will be displayed in MATLAB’s Command window while installation is in progress

-	Confirm set up by typing “mex -setup” in command window to verify installation following completion (Please check MATLAB and Simulink requirements on the same page using the link above as well)

![image](https://user-images.githubusercontent.com/79542683/215545130-382b21e3-2efb-4edd-b68b-29f386fbbd06.png)

-	Majority of the other installation procedures would be done using “Command Prompt Window”. This can easily be accessed by typing “Command window” in the search tile on your operating system

-	Download CMake using the link (https://cmake.org/download/). I recommend using the Windows x64 Installer option to enable you make your own installation settings. Make sure it is available for all users of the PC. Confirm that cmake is on the PC by typing “cmake” on command prompt

-	Finally, ensure that Microsoft Visual Studio is installed on the machine. Please note that Microsoft Visual Studio is different from Microsoft Visual Studio Code. Again, compatibility should be confirmed in the users’ guide manual provided by NOMAD developers

-	Download your preferred NOMAD version and unzip the file. In the root folder, get a link which is done by easily double-clicking on the pane which bears the opened folder.

![image](https://user-images.githubusercontent.com/79542683/215545225-d8392890-6673-4928-9f43-343c913d0d6e.png)

-	The interface build is managed by CMake that can be run *at NOMAD root*. Use the command “cd copiedAddress” command in command prompt to change the directory to the location you have copied above (replace copiedAddress with the link obtained)

-	To build the MATLAB interface, force the use of the 64bit version of the compiler with the command:

cmake -DTEST_OPENMP=OFF -DBUILD_INTERFACE_MATLAB=ON -S . -B build/release -A x64

-	The above might take some minutes. Following the completion, use the command below:

cmake --build build/release --config Release

to proceed with configuration

-	Then, finally, use the command
cmake --install build/release 
which must be run before using the Matlab nomadOpt function. You can expect to see the following during the build process:

![image](https://user-images.githubusercontent.com/79542683/215545288-bd7975c8-33ad-404f-ad73-7a9b78a944b3.png)
![image](https://user-images.githubusercontent.com/79542683/215545301-67301ad9-a8cb-42db-ab47-ac54c3cbfb99.png)
![image](https://user-images.githubusercontent.com/79542683/215545325-5e203dd9-3a51-4e63-b754-a6ca209c400e.png)

-	Make sure to add NOMAD subfolders on MATLAB before testing the installation. On MATLAB’s Home, use the “Set Path” menu to “Add with Subfolders” the whole NOMAD folder so that functions can easily be accessed

-	Run examples provided in the installation folder to confirm that the functions can now be called easily from MATLAB’s command window. For example, trying to solve problem three (3) should give you something similar to:

![image](https://user-images.githubusercontent.com/79542683/215545363-7a689b32-4780-4e88-b441-c628eca028d0.png)

**Comment by ctribes** [comment]
Thanks for sharing

**Comment by Arrowstar** [comment]
It would probably be helpful if some of these tips and tricks (or perhaps this whole page, verbatim) made it into the documentation for the MATLAB build of NOMAD.

**Comment by ctribes** [comment]
I am thinking to have it in an appendix for the next release.

**Comment by ultimatecheun** [comment]
> Thanks for sharing

Please don't mention Christophe.
My pleasure...

**Comment by ultimatecheun** [comment]
> It would probably be helpful if some of these tips and tricks (or perhaps this whole page, verbatim) made it into the documentation for the MATLAB build of NOMAD.

Yes yes, that would be very much helpful for new users, I believe.

I understand that you most probably were experiencing some challenges as well.
Hopefully, you've been able to eventually build your MATLAB interface using the above guide.

**Comment by ctribes** [comment]
The text and figures have been included in the user guide of the new version
https://nomad-4-user-guide.readthedocs.io/en/latest/Appendix.html#guide-to-build-matlab-interface-for-windows-using-mingw
