### ISSUE TITLE
NOMAD does not provide blocks of points to eval for parallel processing

### ISSUE THREAD

**Issue by Arrowstar** [bbopt/nomad#131]
Despite setting BB_MAX_BLOCK_SIZE to a number greater than 1, I cannot get NOMAD to provide more than 1 point for evaluation at a time.  I am using the MATLAB interface for NOMAD.  Please advise on what other parameters I need to set in order to use block sizes greater than 1.  Thank you!

EDIT: I should add that my options structure looks like the following:

> K>> o
> 
> o = 
> 
>   struct with fields:
> 
>           direction_type: 'ortho n+1 quad'
>         stop_if_feasible: '0'
>                nm_search: '0'
>           display_degree: '2'
>         display_all_eval: '1'
>        bb_max_block_size: '100000000000'
>            DISPLAY_STATS: 'BBE TIME OBJ CONS_H H_MAX'
>     SGTELIB_MODEL_SEARCH: 'false'
>           bb_output_type: 'OBJ PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB PB'

I am calling NOMAD through the typical MATLAB interface:

`[x,fval,exitflag,iter,nfval] = nomadOpt(problem.objective, problem.x0, problem.lb, problem.ub, o, iterFun);`

**Comment by jan-provaznik** [comment]
This would be because [matlabEval](https://github.com/bbopt/nomad/blob/master/interfaces/Matlab_MEX/Source/nomadmex.cpp) of MATLAB interface does not implement [Evaluator::eval_block](https://github.com/bbopt/nomad/blob/master/src/Eval/Evaluator.hpp). No matter what value you set `bb_max_block_size` to, the interface will only evaluate the blackbox on single-point basis.

Perhaps this could become a feature request?

**Comment by Arrowstar** [comment]
> This would be because [matlabEval](https://github.com/bbopt/nomad/blob/master/interfaces/Matlab_MEX/Source/nomadmex.cpp) of MATLAB interface does not implement [Evaluator::eval_block](https://github.com/bbopt/nomad/blob/master/src/Eval/Evaluator.hpp). No matter what value you set `bb_max_block_size` to, the interface will only evaluate the blackbox on single-point basis.
> 
> Perhaps this could become a feature request?

Thank you for the explanation.  Yes, please, I would appreciate this getting added as a feature request.  I was unaware this wasn't functional in the MATLAB interface for NOMAD 4 (as far as I'm aware it's not mentioned in any documentation anywhere).  My application really benefits from parallel processing the evaluations, so if there's any way this could get moved up the priority list, that would be awesome.  Thank you.

**Comment by ctribes** [comment]
> Thank you for the explanation. Yes, please, I would appreciate this getting added as a feature request. I was unaware this wasn't functional in the MATLAB interface for NOMAD 4 (as far as I'm aware it's not mentioned in any documentation anywhere). My application really benefits from parallel processing the evaluations, so if there's any way this could get moved up the priority list, that would be awesome. Thank you.

I will look into that quickly. If I remember correctly, it's a matter of uncommenting and fixing some pieces of code. But most importantly, testing!

**Comment by Arrowstar** [comment]
> > Thank you for the explanation. Yes, please, I would appreciate this getting added as a feature request. I was unaware this wasn't functional in the MATLAB interface for NOMAD 4 (as far as I'm aware it's not mentioned in any documentation anywhere). My application really benefits from parallel processing the evaluations, so if there's any way this could get moved up the priority list, that would be awesome. Thank you.
> 
> I will look into that quickly. If I remember correctly, it's a matter of uncommenting and fixing some pieces of code. But most importantly, testing!

Thank you, I would appreciate it!  I'm happy to help with testing if updated source code can be provided to me.

**Comment by ctribes** [comment]
A branch with the evaluation of block of points in Matlab is available PR #134.

@Arrowstar you can test it. I will wait for your feedback before merging into the develop branch and the master branch.

**Comment by Arrowstar** [comment]
> A branch with the evaluation of block of points in Matlab is available PR #134.
> 
> @Arrowstar you can test it. I will wait for your feedback before merging into the develop branch and the master branch.

It appears to be working.  I was able to check out the branch, compile NOMAD's mex interface, and run one of my problems with it.  Unfortunately, I see that the callback function doesn't work with parallel processing yet.  This is critical for my applicable (both for providing feedback on optimizer status and for user stop control).  Is there any way you can get user callback functions added as well?  They don't need to be called after every point is executed.  After every block would be satisfactory for me.

Thank you for this! :)

**Comment by ctribes** [comment]
Thanks for the feedback.
I will work on the callback.

**Comment by Arrowstar** [comment]
> Thanks for the feedback. I will work on the callback.

Thank you!

**Comment by ctribes** [comment]
It is done.

**Comment by Arrowstar** [comment]
> It is done.

Thanks!  It works, but there's an issue.  The "iteration" field of the optimValues structure that's passed into the callback function does not increment uniformly.  Every time the function is called it should go from 0, to 1, to 2, to 3, etc.  Instead, the iteration numbers it produces are wild.  I suspect the current code is just taking the number of evals from the previous block and adding it to the previous iteration number, but I can't confirm.  In any event, the current behavior is confusing and doesn't really work as users might expect.

**Comment by ctribes** [comment]
It is suppose to be the current number of evaluation done.
It seemed ok on the example. I will check more carefully.

**Comment by Arrowstar** [comment]
In the optimValues structure there are two fields:

optimValues.iteration
optimValues.funccount

I think these might be getting set to the same number accidently.  They read the same for me, but I would expect "iteration" to be much less than "funccount".

**Comment by ctribes** [comment]
I searched for an optimValues structure but I don't see any in the Matlab interfaces. 

When I run the example $NOMAD_HOME/interfaces/Matlab_MEX/example_block_eval with the callback, the evaluation counter is ok. Here is what I obtain:
![image](https://user-images.githubusercontent.com/26410818/221230083-121c6369-0650-4ad0-a550-d2b188015b55.png)

**Comment by Arrowstar** [comment]
> I searched for an optimValues structure but I don't see any in the Matlab interfaces.
> 
> When I run the example $NOMAD_HOME/interfaces/Matlab_MEX/example_block_eval with the callback, the evaluation counter is ok. Here is what I obtain: ![image](https://user-images.githubusercontent.com/26410818/221230083-121c6369-0650-4ad0-a550-d2b188015b55.png)

I have to apologize, the struct() I was talking about actually was something I put together in my own software a long while back.  You can disregard my comment, I have a bug in my own code it looks like.

As far as I'm aware, all the MATLAB parallel processing functionality is working as I expect now.

**Comment by ctribes** [comment]
@Arrowstar 
No worries. I will merge the branch in the Develop.

**Comment by Arrowstar** [comment]
I assume this can be closed after the release of 4.4?

**Comment by ctribes** [comment]
I am confident that PR #134 is now in v.4.4.
