### ISSUE TITLE
LH_SEARCH: Unrecongized Parameter

### ISSUE THREAD

**Issue by Arrowstar** [bbopt/nomad#135]
When trying to use the LH_SEARCH parameter in the MATLAB interface, I receive the following error:

```
NOMAD Parameter Error:
NOMAD::Exception thrown (/home/aharden/Documents/nomad-v4.3.1/src/Param/RunParameters.cpp, 152) Unrecognized parameters in file Standard Input:
line 0: Unrecognized parameter: LH_SEARCH
```
My options structure looks like this:

```
             direction_type: 'ortho 2n'
           stop_if_feasible: 0
    VNS_MADS_SEARCH_TRIGGER: 0.75
            VNS_MADS_SEARCH: 1
                  nm_search: 0
             display_degree: 2
           display_all_eval: 1
          BB_MAX_BLOCK_SIZE: 100
              DISPLAY_STATS: 'BBE TIME OBJ CONS_H H_MAX'
       SGTELIB_MODEL_SEARCH: 0
                  LH_SEARCH: [10000 100]
```

Any ideas?  Is this just not implemented yet?

**Comment by ctribes** [comment]
I am just not sure what causes this error. I cannot replicate it on my side.

Please note that nomadset function is not used anymore.
All options name and value are passed as string:

`params = struct('display_all_eval','true','display_degree','3','max_bb_eval','30','direction_type','ortho 2n','bb_output_type','OBJ PB PB','bb_max_block_size','4','LH_SEARCH','10 0'); 
`

Almost all parameters accepted in a parameter file read by nomad.exe can be passed into the matlab struct.

**Comment by Arrowstar** [comment]
> I am just not sure what causes this error. I cannot replicate it on my side.
> 
> Please note that nomadset function is not used anymore. All options name and value are passed as string:
> 
> `params = struct('display_all_eval','true','display_degree','3','max_bb_eval','30','direction_type','ortho 2n','bb_output_type','OBJ PB PB','bb_max_block_size','4','LH_SEARCH','10 0'); `
> 
> Almost all parameters accepted in a parameter file read by nomad.exe can be passed into the matlab struct.

This was it, I just needed to pass in the numbers as a string.  Thanks!
