### ISSUE TITLE
Passing in initial points with evaluation?

### ISSUE THREAD

**Issue by TianningGao** [bbopt/nomad#137]
How can I pass a set of initial points with their evaluation into NOMAD? I'm using python and the PyNomad interface.

I have a set of initial points and their evaluations stored in two numpy arrays. The only way I found in the user guide is through 'X0' parameter but that still doesn't include the evaluations.

**Comment by ctribes** [comment]
The way to pass initial points with their evaluation is by using a cache file from a previous run. It is briefly mentioned in the user guide, in the section about X0 (https://nomad-4-user-guide.readthedocs.io/en/latest/HowToUseNomad.html#x0). 

I attached an example in Python. When X0 is empty, Nomad will use the cache file provided (see "CACHE_FILE" in parameters) and put new evaluation points in it.
[runTest_cacheX0.py.txt](https://github.com/bbopt/nomad/files/11311432/runTest_cacheX0.py.txt)

**Comment by TianningGao** [comment]
OK, thank you.
