### ISSUE TITLE
Plans for F_TARGET in v4

### ISSUE THREAD

**Issue by osborn9** [bbopt/nomad#146]
Are there plans to have similar functionality in v4 as F_TARGET to terminate if the objective function drops below a value?

Thanks!

**Comment by ctribes** [comment]
It will be available in the next release next November.

Please note that, if you are using Nomad in library mode, user callbacks are available. These callbacks can be used to stop the algorithm on criterion that user implement. An example of user callback is given in $NOMAD_HOME/examples/advanced/library/Restart
