### ISSUE TITLE
documention for python interface

### ISSUE THREAD

**Issue by prasadkumar0590** [bbopt/nomad#15]
Is there any python interface for nomad. If yes can you please provide  documentation. It would be great help for us. You help is very much appreciated.

**Comment by wlav** [comment]
> Is there any python interface for nomad.

You are posting to an issue tracker that provides a python interface to NOMAD, so what do you think? I already pointed you to upstream NOMAD which has a python interface as well. I already pointed you to documentation for both.

**Comment by montplaisir** [comment]
The Python interface is located in the directory interfaces/PyNomad. Basically, the Python interface is the same in NOMAD 4 as in NOMAD 3. There is some information about it in the NOMAD 3 user guide, as well as in the file interfaces/PyNomad/readme.txt. To download NOMAD 3, go to https://www.gerad.ca/nomad/.

**Comment by prasadkumar0590** [comment]
Thank you fror quick response.
If we want run python files which are located in "nomad.3.9.0\examples\interfaces\pyNomad_Beta" folder do we need to install nomad software from this url `https://www.gerad.ca/nomad/`. your help is greatly appreciated.
