### ISSUE TITLE
PSD-MADS - Cannot open include file: 'mpi.h': No such file or directory

### ISSUE THREAD

**Issue by prasadkumar0590** [bbopt/nomad#17]
trying to run parallel proceesing with PSD-MADS. I am trying to build the psdmas.sln file getting below error.

 Cannot open include file: 'mpi.h': No such file or directory

We have installed MSMPI also, still we are getting this error

OS: Windows
visual studio - 2017

1- Open the psdmads Microsoft VisualStudio solution located in %NOMAD_EXAMPLES%\VisualStudio
2- Build the solution
3- Open a VisualStudio command shell
4- Change the directory to one of the problem directories in %NOMAD_EXAMPLES%\tools\PSD-MADS\problems
5- Build the blackbox executable with the command: cl bb.cpp
6- Start the optimization: mpirun -np p ../../psdmads.exe param.txt bbe ns
   p: Number of processors to use
   bbe: Maximal number of evaluations performed by each slave
   ns: Number of variables considered by the slaves.
   Ex: mpiexec -n 4 ..\..\psdmads.exe param.txt 20 3

**Comment by ctribes** [comment]
This repositery is for NOMAD 4. The building procedure for this version is not yet available for Windows. 

The reported issue is for Nomad 3.9.1. Use nomad@gerad.ca to report a bug/issue on Nomad 3.
