### ISSUE TITLE
Wheels for Python 3.12

### ISSUE THREAD

**Issue by jan-provaznik** [bbopt/nomad#175]
It would be nice to upload a release for Python 3.12 onto PyPi. The interface builds without any issues against Python 3.12.4 on Linux. I believe this should be as easy as running the [appropriate workflow](https://github.com/bbopt/nomad/actions/workflows/pypi.yml) at your convenience.

**Comment by ctribes** [comment]
I have updated the PyNomadBBO for Linux on PyPi (Python 3.12 and 3.13).
