### ISSUE TITLE
Feature Request: Port the MATLAB Interface from NOMAD 3.x to NOMAD 4

### ISSUE THREAD

**Issue by Arrowstar** [bbopt/nomad#19]
As the title says, please consider porting the MATLAB interface for NOMAD from NOMAD 3.x to NOMAD 4.0.  I have MATLAB code that uses NOMAD and I would love to try the latest beta release.  Thank you for your kind consideration.

**Comment by montplaisir** [comment]
Thank you for your suggestion! We added it to our todo list.
