### ISSUE TITLE
GRANULARITY parameter causes errors for specific X0 values

### ISSUE THREAD

**Issue by Tinynja** [bbopt/nomad#2]
Hello,

First of all I would like to thank you for developping NOMAD, it is very useful and easy to use. I'm currently trying to use NOMAD 3.9.1 (Windows 10 64-bit, 19041.450) to optimize a problem of mine, but I'm having a little bit of trouble with the GRANULARITY parameter. Here is the sample parameters file I'm using:

    DIMENSION		1
    BB_EXE			bb.exe
    BB_OUTPUT_TYPE		OBJ
    X0			( #### )
    GRANULARITY		0.1

After some testing, I found out that values of #### between 1024 and 2047 with a decimal place (e.g. 1024.1) and between 2458 and 4095 with a decimal place (e.g. 4095.1) (and probably other ranges of values for ####) cause the following error:

    ERROR: Invalid Parameter (..\src\Parameters.cpp, 5951):  invalid granularity of variable 0: 0.1 vs initial value: 4095.1

For values in those ranges, I have to set the GRANULARITY parameter to at least 0.000001 to not have that error. However, a value of 1024.2 doens't give that error. If I understood the GRANULARITY parameter correctly, this doesn't seem like an expected behavior.

Any help is appreciated!

**Comment by ctribes** [comment]
Thanks for reporting this odd behaviour. We will investigate.

**Comment by ctribes** [comment]
**Please note that this Github repository is for the public version of Nomad 4.** The reported behaviour happens only in Nomad 3. For reporting Nomad 3 bugs we suggest to use **nomad@gerad.ca**.

About the bug. For Nomad 3.9.1, we have modified the check procedure for x0, lb and ub when granularity is provided. This new version of the test is more robust. This modification will be available in the next release (Nomad 3.9.2). We provide in this comment the modified version in attachment. The file must be renamed from Parameters.txt to Parameters.cpp (GitHub constraint!) and Nomad build must be performed.
[Parameters.txt](https://github.com/bbopt/nomad/files/5143032/Parameters.txt).
