### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by andrescodas** [bbopt/nomad#31]
The size of this repository is over 300 Mb, mostly because of the compiled docs.  I'm wondering if you could shrink it, by making the compiled docs available by other means.  This might benefit users with poor connection, by reducing network traffic and storage.

Thanks for making this great tool available here!

**Comment by ctribes** [comment]
Thanks for the comment. 
We will remove the whole doxygen documentation from the repositery. This should significantly reduce the size.

**Comment by montplaisir** [comment]
Hi Andres!
Doxygen compiled files are now removed in the develop branch.

**Comment by andrescodas** [comment]
thanks a lot for the prompt response.

Just note that the repository keeps the doc files in its history records after [this solution](https://github.com/bbopt/nomad/pull/32/commits/e1ccd80dd9be5c536679e27c213e78b3d5c0ba7b). See [this article](https://medium.com/@sangeethkumar.tvm.kpm/cleaning-up-a-git-repo-for-reducing-the-repository-size-d11fa496ba48#:~:text=remove%20the%20file%20from%20your,unused%20data%20using%20git%20gc) for details.

[This api](https://api.github.com/repos/bbopt/nomad) shows the current repo size, under the key 'size' (in Kb)

However, if all we need is the latest state of the develop branch, we can add some parameters to the clone command:

```
git clone --single-branch --branch develop --depth 1 https://github.com/bbopt/nomad.git
```

to prevent downloading the whole git history.  With that the download size is 7.5 Mb :)

**Comment by montplaisir** [comment]
Thank you for your post, that command may be useful for other users indeed!
