### ISSUE TITLE
nomad .input file serial number

### ISSUE THREAD

**Issue by prasadkumar0590** [bbopt/nomad#33]
Can we add serial number to .input file which is input for bbe. Is  there any way to configure serial number to input file please let us know. your help very much appreciated

we are using bbe for python script

**Comment by ctribes** [comment]
Hello,

In Nomad 4, we cannot add an extra information (like a serial number or a tag number) in the content of the input file used by the blackbox. The input file must contain only the design variable values.

Also, it is not possible to add this information in the input file name. This functionality is not yet implemented in Nomad 4 but will be in the future. However, this functionality is available in Nomad 3. Please note that Nomad 3 is not available in Github, it can be downloaded at www.gerad.ca/nomad). In Nomad 3, the evaluation tag can be added to the input file name using the BB_INPUT_INCLUDE_TAG parameter. 

Best regards
