### ISSUE TITLE
Add support for SOLUTION_FILE.

### ISSUE THREAD

**Issue by kilasuelika** [bbopt/nomad#4]
This parameter is shown in user guide ver3.9. However in latest version, it's an unrecognized parameter. Writing the final solution to a file for post processing is very common.

**Comment by montplaisir** [comment]
Hi @kilasuelika , we will add this parameter in the next Beta. Thank you for your input!

For any question or comments, email us: nomad@gerad.ca

**Comment by montplaisir** [comment]
SOLUTION_FILE is in the current Beta-2.0.1.
