### ISSUE TITLE
Make Nomad 4 installer for end users

### ISSUE THREAD

**Issue by jennywang123** [bbopt/nomad#51]
Hello Nomad team,

for Nomad 3.9.1, there is an installer for end user so the user can install with a simple click of the installer file. 

Could we also have an installer for Nomad 4 for end user? Typically I am asking for Windows OS.

Thank you,
Jenny

**Comment by ctribes** [comment]
Hello Jenny,

The windows installer for Nomad 3.9.1 has some flaws. This is why we have not use the same installer for Nomad 4.
For the next release I will investigate what would be a good way to provide binaries for Nomad 4.

Best regards
Christophe

**Comment by jennywang123** [comment]
Ok, thank you for the response. I think it will be easier to have an installer.

**Comment by ctribes** [comment]
A collection of binaries are now available for the tagged release of Nomad 4.2 and above.
