### ISSUE TITLE
dead link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by SobhanMP** [bbopt/nomad#69]
https://github.com/bbopt/nomad/blob/master/ROADMAP.md is the link to the roadmap not https://github.com/bbopt/nomad/ROADMAP.md

**Comment by ctribes** [comment]
Can you be more specific ?

**Comment by SobhanMP** [comment]
in the second last paragraph of https://raw.githubusercontent.com/bbopt/nomad/master/CONTRIBUTING.md 

> ### Features / Enhancements
If the feature is already in the list of issues, input should be added to that issue. Otherwise, a new issue may be opened. Please check the [roadmap](https://github.com/bbopt/nomad/ROADMAP.md) for upcoming features.

the link to ROADMAP.md is wrong.

**Comment by ctribes** [comment]
Got it. 
Thanks.
