### ISSUE TITLE
Is there a way to terminate the costly blackbox evaluation in advance?

### ISSUE THREAD

**Issue by windless1015** [bbopt/nomad#77]
Hi, I am using the NOMAD3.9.1 to evaluate a blackbox task.  It will drop to obvious local optimum somethings. I notice that the outputs are nearly same or even get very small differences at the end of the evaluation. In some conditions, it will last for hundres of iterations. More compuating resources  and time have been put into the final result, but the result has satisfied the requirements. So, my question is how can I alter some arguments or is there a mechanism to terminate the evaluaion in NOMAD to solve this problem? I know user can use CTRL-C to terminate the algorithm mamually. Thank you very much.

**Comment by ctribes** [comment]
Please note that this Git is for Nomad 4. Nomad 4 is a **completely new version** of Nomad. To have support about Nomad 3, please send email to **nomad@gerad.ca**.

Here are a few things that can be done in Nomad 3 to prevent unnecessary blackbox evaluations.
1- Premature stop of the optimization with CTRL-C or kill the Nomad process. 
2- Kill costly blackbox evaluations manually. Nomad will tag these evaluations as "failed" and will continue. 
3- Specify parameters to have a better control of stopping (check on the user guide for details):
          - MAX_BB_EVAL
          - MAX_TIME
          - GRANULARITY
          - MIN_MESH_SIZE
          - MAX_CONSECUTIVE_FAILED_ITERATIONS
          - F_TARGET

Some parameters can also help for exploring the design space and get out of local optimum:
         - VNS_SEARCH
         - LH_SEARCH
         - MODEL_SEARCH SGTELIB

**Comment by windless1015** [comment]
Thank you very much. Appreciate your reply. Have a good one.
