### ISSUE TITLE
cmake does not respect the CMAKE_INSTALL_PREFIX variable?

### ISSUE THREAD

**Issue by SobhanMP** [bbopt/nomad#81]
`set(CMAKE_INSTALL_PREFIX ${PROJECT_BINARY_DIR} CACHE PATH "..." FORCE) `
in the cmake file seems to just overwrite it.

**Comment by ctribes** [comment]
Fixed to get the intended behaviour:
Default CMAKE_INSTALL_PREFIX is in $PROJECT_BINARY_DIR if not specified by user. 

Binaries for examples are still installed in $NOMAD_HOME/examples.

**Comment by SobhanMP** [comment]
:+1:
